# Generated by Django 6.1 on 2026-08-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Subject', 'Chapter', 'Year'", max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tag Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="e.g., 'Operating Systems', '2024'", max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tags.tagcategory')),
            ],
            options={
                'unique_together': {('category', 'value')},
            },
        ),
    ]
