# Generated by Django 6.1.1 on 2026-09-23 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qna", "0005_comment_is_deleted_comment_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceMaterialChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Chapter title (e.g., "Graph Theory")', max_length=255
                    ),
                ),
                (
                    "chapter_number",
                    models.PositiveIntegerField(
                        help_text="Chapter number within the source material",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of pages in this chapter (optional)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this chapter was created",
                    ),
                ),
                (
                    "source_material",
                    models.ForeignKey(
                        help_text="The source material (book/course) this chapter belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="qna.sourcematerial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Material Chapter",
                "verbose_name_plural": "Source Material Chapters",
                "db_table": "curriculum_sourcematerialchapter",
                "ordering": ["source_material", "chapter_number"],
                "indexes": [
                    models.Index(
                        fields=["source_material", "chapter_number"],
                        name="curriculum__source__2dccf0_idx",
                    )
                ],
                "unique_together": {("source_material", "chapter_number")},
            },
        ),
    ]
