# Generated by Django 6.1 on 2026-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0003_answer_status_historicalanswer_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestededit",
            name="removed_attachment_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of FileAttachment IDs to delete upon approval.",
            ),
        ),
    ]
