# Generated by Django 6.1 on 2026-08-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0003_alter_fileattachment_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_official",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="is_official",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalquestion",
            name="is_official",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="is_official",
            field=models.BooleanField(default=False),
        ),
    ]
