# Generated by Django 6.1 on 2026-08-28 18:43

import uuid
from django.db import migrations, models


def backfill_blank_emails(apps, schema_editor):
    """
    Assign a unique placeholder email to any existing user with a blank email
    so that the unique constraint on email can be applied without errors.
    These users were created during development before email was required.
    """
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(email=''):
        user.email = f'placeholder-{uuid.uuid4()}@no-email.invalid'
        user.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(
                default=False,
                help_text='Whether the user has confirmed ownership of their email address.',
            ),
        ),
        # Backfill blank emails before adding the unique constraint
        migrations.RunPython(backfill_blank_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
